name: hidock-mic-trigger
options:
  bundleIdPrefix: com.hidock.tools
  deploymentTarget:
    macOS: 13.0
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
targets:
  hidock-mic-trigger:
    type: application
    platform: macOS
    sources:
      - Sources
      - Assets.xcassets
    settings:
      INFOPLIST_KEY_LSUIElement: YES
      INFOPLIST_KEY_NSMicrophoneUsageDescription: "This app launches hidock-mic-trigger to keep the HiDock mic active when your USB mic is in use."
      PRODUCT_NAME: hidock-mic-trigger
    info:
      path: Info.plist
      properties:
        CFBundleName: HiDock Mic Trigger
        CFBundleDisplayName: HiDock Mic Trigger
        CFBundleIdentifier: com.hidock.tools.hidock-mic-trigger
        CFBundleExecutable: hidock-mic-trigger
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSUIElement: true
        NSMicrophoneUsageDescription: "This app launches hidock-mic-trigger to keep the HiDock mic active when your USB mic is in use."
